### ISSUE TITLE
Introduce a new keyword argument to the show_page_content templatetag

### ISSUE THREAD

**Issue by markotibold** [ridethepony/django-fiber#166]
Currently Django Fiber supports content templates. These can be assigned to a specific PageContentItem by an authorized user via the frontend.

In some cases though you, might want to be able to setup a default template. And optionally let a user choose a different one.

So a usage example would be:

```
{% load fiber_tags %}
...
{% show_page_content "sidebar" template="content/strict_side_contentt.html" %}
```

In the above example the content template would bu unchangeable.

Another example might be where the user is allowed to assign a different content template:

```
{% load fiber_tags %}
...
{% show_page_content "sidebar" default_template="content/default_side_contentt.html" %}
```

I think this feature could come in pretty handy.

Opinions anyone?

**Comment by bsimons** [comment]
This issue has been open for such a long time, but nobody did anything about it. So we are closing it.
