### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by mbraak** [ridethepony/django-fiber#179]
Let's add Python 3 support.

This is implemented in: https://github.com/mbraak/django-fiber/tree/python3
- This drops Django 1.3 support.
- Uses experimental branches of django-mptt and django-compressor.

**Comment by cnk** [comment]
So there have been (at least) 2 attempts at this - but both branches have been removed. @xj9 could you give me some idea of the best place to start to create a version that will get merged into the main repo?

**Comment by bsimons** [comment]
The current dev branch is Python 3 compatible, if you are up to it could you please check and confirm that is works?
