### ISSUE TITLE
Problems when django is deployed at a non-root url

### ISSUE THREAD

**Issue by jccha** [ridethepony/django-fiber#195]
When django is deployed at a non-root url of a website, some features of django-fiber do not work properly.  Most problems are related to wrong urls, which seem to be generated under the assumption that django is deployed at the root.

What I found are:
1. The side menu for frontend is still shown when it is in the backend side (admin).
2. Navigation menu items in the side menu do not work.
3. Some fiber admin pages malfunction: in "Change content item", ckeditor is not shown.  In "Change page", the layout is broken (much narrower than usual).
4. The link to frontend always takes us to the root url of the website.

Looking at the code quickly, I've found that 1 and 3 are resolved by replacing request.path_info by request.path in is_django_admin() in middleware.py.

**Comment by dbunskoek** [comment]
I see nothing inappropriate from your side :)
We just never got around to answering you, sorry... I never deploy Django at a non-root URL, so I'm sorry but I can't help you with that.
I'm closing this issue for now.
