### ISSUE TITLE
Inaccurate sitemap lastmod/what does it mean for a Page to be updated

### ISSUE THREAD

**Issue by frankier** [ridethepony/django-fiber#204]
lastmod() in sitemaps.py uses Page.updated directly. The timestamp "updated" on the model Page is only updated when Page is actually saved, but when a ContentItem or PageContentItem is saved this also updates the end result page, meaning lastmod should be later.

One approach would be to big the latest of all the ContentItem.update fields and Page.updated. This doesn't take into account the situation where neither ContentItems or Pages are actually saved, but they are swapped, but perhaps this is acceptable. Or an updated field could also be added on PageContentItem.

Another approach would be to override the save() methods of ContentItem and PageContentItem to save the Page, "touch"ing the Page.updated timestamp. This might be considered a little hacky though.

**Comment by dbunskoek** [comment]
I like the `override the save() methods of ContentItem and PageContentItem to save the Page,"touch"ing the Page.updated timestamp` way. If you could provide a pull request that would be great!

**Comment by dbunskoek** [comment]
Closing this for now...
