### ISSUE TITLE
Django-Fiber 1.2 is broken with djangorestframework v3.x

### ISSUE THREAD

**Issue by surfer26th** [ridethepony/django-fiber#217]
Had to revert to djangorestframework 2.4.8

Issue with djangorestframework v.3.X seems to be the following: 

Fiber calls callingpagination.BasePaginationSerializer in pagination.py (in djangorestframework), but djangorestframework no longer includes that method in pagination.py (at least it is not in djangorestframework v3.2.3. They changed the names of the methods beginning in v3.X !!) Can't believe they did this, since it must break compatibility with a lot of existing code)

**Comment by urban011** [comment]
Any hope of getting DRF 3.x compatibility? I would hate to have to choose between the two. Not sure how to fix this off hand.

**Comment by richardbarran** [comment]
FYI I have opened a pull request for upgrading djangorestframework v3.x - #237

**Comment by bsimons** [comment]
The current dev branch is compatible with DRF >= 3.4, if you are up to it could you please check and confirm that is works?
