### ISSUE TITLE
Increase Django 1.9 compatibility - do not trigger RemovedInDjango19 Warnings

### ISSUE THREAD

**Issue by ryuusenshi** [ridethepony/django-fiber#223]
Running tests produces several RemovedInDjango19 Warnings in Django 1.9. Seeing how Django 1.9 is in beta now and how annoying these warnings are I propose fixing this.

Additionally, it's worth noting that one of these warnings is produced every time a project with fiber installed is run.

**Comment by SpacemanPaul** [comment]
Django 1.9 is now released.  I would like to upgrade, but I'm not even sure if fiber is compatible with 1.9 at this stage?

**Comment by dbunskoek** [comment]
Some work has been done by @jaap3 in the django1.9 branch. It would be great if you could check if this works / what still needs to be done, and help move it forward.

**Comment by bsimons** [comment]
The current dev branch is now compatible with Django 1.9.x, if you are up to it could you please check and confirm that is works?
