### ISSUE TITLE
is it possible to use different editor instead of ckeditor ?

### ISSUE THREAD

**Issue by vladyslav2** [ridethepony/django-fiber#233]
i think right now you can use more better editors, like summor note, quilljs, imperavi redactor and others

any suggestion how hard will be integration with different editor ?

**Comment by bsimons** [comment]
You can have a look at https://github.com/ridethepony/django-fiber/blob/master/docs/advanced-usage.rst#optional-settings:

`FIBER_EDITOR = 'fiber.editor_definitions.ckeditor.EDITOR'`

You can define an editor as in https://github.com/ridethepony/django-fiber/tree/master/fiber/editor_definitions/ and point to it in your settings with `FIBER_EDITOR`
