### ISSUE TITLE
Current status of this project?

### ISSUE THREAD

**Issue by richardbarran** [ridethepony/django-fiber#239]
Hi guys,
I'm wondering what the current status of this project is? The latest commit to the master branch was 9 months ago, and there's been no visible activity for maybe 6 months now - no PRs reviewed or accepted, no issues handled, etc...
Have the original maintainers moved onto other projects? Is Django-Fiber dying?

**Comment by dbunskoek** [comment]
Hi Richard, we just released the new version of Django Fiber (1.4.0). Please read the 'important message' at the top of the README, and then let's discuss the future of Django Fiber in #244 :)
