### ISSUE TITLE
Take proper action upon 401 HTTP response for ajax requests

### ISSUE THREAD

**Issue by h3** [ridethepony/django-fiber#64]
When a user is not logged in but has a front admin dialog open and click save, unwanted things happens. Like closing the window  letting the user think it has been saved (while leaving the overlay) or simply doing nothing (image upload).

Since fiber ships with a login dialog, I think it should be fairly easy to open it when such responses occur.

**Comment by bsimons** [comment]
This issue has been open for such a long time, but nobody did anything about it. So we are closing it.
